---
title: "distribution of cheaters"
output: html_notebook
---

```{r}
library(ggplot2)
library(tidyverse)
```

```{r}
n <- 1000  # number of loggers
m <- 1000 # number of rounds where logger wants to cheat
p0 <- 0.5 # starting probability 
p <- rep(p0, times=n)  # set starting p 
q <- 0.5 # set probability of being caught 
sanctionLevel <- 0.1


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= p[i]){ # cheated
  if(runif(1) <= q){
    p[i] <- p[i] - p[i]*sanctionLevel
  }else{
    p[i] <- (1 + p[i])*sanctionLevel
  }
}
  }
}

data1<- data.frame(Sanc.1=p)

p <- rep(p0, times=n)  # set starting p 
sanctionLevel <- 0.5


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= p[i]){ # cheated
  if(runif(1) <= q){
    p[i] <- p[i] - p[i]*sanctionLevel
  }else{
    p[i] <- (1 + p[i])*sanctionLevel
  }
}
  }
}
data1$Sanc.5<- p


p <- rep(p0, times=n)  # set starting p 
sanctionLevel <- 0.3


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= p[i]){ # cheated
  if(runif(1) <= q){
    p[i] <- p[i] - p[i]*sanctionLevel
  }else{
    p[i] <- (1 + p[i])*sanctionLevel
  }
}
  }
}
data1$Sanc.3<- p

p <- rep(p0, times=n)  # set starting p 
sanctionLevel <- 0.7


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= p[i]){ # cheated
  if(runif(1) <= q){
    p[i] <- p[i] - p[i]*sanctionLevel
  }else{
    p[i] <- (1 + p[i])*sanctionLevel
  }
}
  }
}
data1$Sanc.7<- p

p <- rep(p0, times=n)  # set starting p 
sanctionLevel <- 0.9


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= p[i]){ # cheated
  if(runif(1) <= q){
    p[i] <- p[i] - p[i]*sanctionLevel
  }else{
    p[i] <- (1 + p[i])*sanctionLevel
  }
}
  }
}
data1$Sanc.9<- p

p <- rep(p0, times=n)  # set starting p 
sanctionLevel <- 0.5
q<- 0.1


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= p[i]){ # cheated
  if(runif(1) <= q){
    p[i] <- p[i] - p[i]*sanctionLevel
  }else{
    p[i] <- (1 + p[i])*sanctionLevel
  }
}
  }
}

data1$mon.1<-p

p <- rep(p0, times=n)  # set starting p 
q<- 0.3


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= p[i]){ # cheated
  if(runif(1) <= q){
    p[i] <- p[i] - p[i]*sanctionLevel
  }else{
    p[i] <- (1 + p[i])*sanctionLevel
  }
}
  }
}

data1$mon.3<-p


p <- rep(p0, times=n)  # set starting p 
q<- 0.7


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= p[i]){ # cheated
  if(runif(1) <= q){
    p[i] <- p[i] - p[i]*sanctionLevel
  }else{
    p[i] <- (1 + p[i])*sanctionLevel
  }
}
  }
}

data1$mon.7<-p

p <- rep(p0, times=n)  # set starting p 
q <- 0.9


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= p[i]){ # cheated
  if(runif(1) <= q){
    p[i] <- p[i] - p[i]*sanctionLevel
  }else{
    p[i] <- (1 + p[i])*sanctionLevel
  }
}
  }
}
data1$mon.9<- p

```

```{r}
cheatProb_distribution<-gather(data1, key="variable", value="cheaters")


save(cheatProb_distribution, file="./allData_IS/cheatProb_distribution.RData")

library(gridExtra)
viz_mon<-cheatProb_distribution%>%filter(variable=="mon.1"|variable=="mon.9"|variable=="Sanc.5"|variable=="mon.3"|variable=="mon.7")%>%ggplot()+geom_histogram(aes(x=cheaters, fill=variable), position="dodge", binwidth = 0.2)+
  xlim(-0.1,1)
  
viz_sanc<-cheatProb_distribution%>%filter(variable=="Sanc.1"|variable=="Sanc.9"|variable=="Sanc.5"|variable=="Sanc.3"|variable=="Sanc.7")%>%ggplot()+geom_histogram(aes(x=cheaters, fill=variable), position="dodge", binwidth = 0.2)+
  xlim(-0.1,1)

grid.arrange(viz_mon, viz_sanc, nrow=1)
```


```{r}
n <- 1000  # number of loggers
m <- 1000 # number of rounds where logger wants to cheat
p0 <- 0.5 # starting probability 
p <- rep(p0, times=n)  # set starting p 
q <- 0.5 # set probability of being caught 
sanctionLevel <- 0.9


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= p[i]){ # cheated
  if(runif(1) <= q){
    p[i] <- p[i] - p[i]*0.5
  }else{
    p[i] <- (1 + p[i])*0.5
  }
}
  }
}

ggplot()+geom_histogram(aes(x=p))
```

not consider probability of cheating 
```{r}
n <- 1000  # number of loggers
m <- 1000 # number of rounds where logger wants to cheat
p0 <- 0.5 # starting probability 
p <- rep(p0, times=n)  # set starting p 
q <- 0.5 # set probability of being caught 


for(j in 1:m){
  for(i in 1:n){
  if(runif(1) <= q){
    p[i] <- p[i]/2
  }else{
    p[i] <- (1 + p[i])/2
  }
  }
}



ggplot()+geom_histogram(aes(x=p))

```
